<template>
  <section class="card">
    <h2>Audit trail</h2>
    <p>Records are generated by the API service on every login or transfer.</p>
    <button @click="reload" class="button">Refresh</button>
    <pre class="audit" v-if="audit.length">{{ audit.join('\n') }}</pre>
    <p v-else>No audit events have been recorded yet.</p>
  </section>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { useBankStore } from '../stores/bank';

const store = useBankStore();
const audit = store.audit;

const reload = async () => {
  await store.fetchAudit();
};

onMounted(async () => reload());
</script>

<style scoped>
.card {
  background: white;
  border-radius: 16px;
  padding: 1.5rem;
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.06);
}

.button {
  background: #2563eb;
  color: white;
  border: none;
  padding: 0.6rem 1.2rem;
  border-radius: 8px;
  cursor: pointer;
  margin: 0.5rem 0 1rem;
}

.audit {
  background: #0f172a;
  color: #e5e7eb;
  border-radius: 8px;
  padding: 1rem;
  max-height: 360px;
  overflow: auto;
  font-size: 0.9rem;
}
</style>
